on: [push]
name: "Builds and Deploys the new Version"
jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install package
        run: |
          npm install
          npm run test:unit
    
  build:
    runs-on: ubuntu-latest
    if: contains(github.ref, 'master')
    needs: [unit-test]
    steps:
      - uses: actions/checkout@master
      - name: Build and Publish Image
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: lol3r/random-wikipedia-frontend:latest
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to production
        uses: appleboy/ssh-action@master
        with:
          host: lol3r.net
          username: leon
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22222
          script: docker pull lol3r/random-wikipedia-frontend:latest && cd personal_compose/ && docker-compose up -d
